### ISSUE TITLE
Install of crypt::Curve25519 failling

### ISSUE THREAD

**Issue by taralon** [ajgb/crypt-curve25519#2]
For Perl:
This is perl 5, version 22, subversion 0 (v5.22.0) built for MSWin32-x86-multi-thread-64int

Cpan, cpanm, and manual install of Crypt::Curve25519 failing due to error(s).  See below for entire cpanm logging:

Work directory is C:\Users\jbarr/.cpanm/work/1464563522.5848
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
Searching Crypt::Curve25519 () on cpanmetadb ...
--> Working on Crypt::Curve25519
Fetching http://www.cpan.org/authors/id/A/AJ/AJGB/Crypt-Curve25519-0.05.tar.gz
-> OK
Unpacking Crypt-Curve25519-0.05.tar.gz
Entering Crypt-Curve25519-0.05
Checking configure dependencies from META.json
Configuring Crypt-Curve25519-0.05
Running Makefile.PL
Checking if your kit is complete...
Looks good
"\x{0084}" does not map to cp437 at C:/Strawberry/perl/lib/ExtUtils/MakeMaker.pm line 1182.
"\x{0084}" does not map to cp437 at C:/Strawberry/perl/lib/ExtUtils/MakeMaker.pm line 1182.
"\x{0084}" does not map to cp437 at C:/Strawberry/perl/lib/ExtUtils/MakeMaker.pm line 1182.
"\x{0084}" does not map to cp437 at C:/Strawberry/perl/lib/ExtUtils/MakeMaker.pm line 1182.
"\x{0084}" does not map to cp437 at C:/Strawberry/perl/lib/ExtUtils/MakeMaker.pm line 1182.
MakeMaker (v7.0401)
Warning (non-fatal): Target 'dynamic' depends on targets in skipped section 'dynamic_lib'
Warning (non-fatal): Target 'static' depends on targets in skipped section 'static_lib'
Generating a dmake-style Makefile
Writing Makefile for Crypt::Curve25519::curve25519donna
Generating a dmake-style Makefile
Writing Makefile for Crypt::Curve25519
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04_01)
Checking if you have File::Spec 0 ... Yes (3.56)
Checking if you have IPC::Open3 0 ... Yes (1.18)
Checking if you have IO::Handle 0 ... Yes (1.35)
Checking if you have Test::More 0 ... Yes (1.001014)
Building and testing Crypt-Curve25519-0.05
cp lib/Crypt/Curve25519.pm blib\lib\Crypt\Curve25519.pm
AutoSplitting blib\lib\Crypt\Curve25519.pm (blib\lib\auto\Crypt\Curve25519)
cd curve25519-donna-master && dmake 
gcc -c      -m32 -s -O2       -DVERSION=\"\"    -DXS_VERSION=\"\"  "-IC:\STRAWB~1\perl\lib\CORE"   curve25519-donna.c
ar cr curve25519-donna.a curve25519-donna.o
rem curve25519-donna.a
Running Mkbootstrap for Crypt::Curve25519 ()
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e chmod -- 644 "Curve25519.bs"
"C:\Strawberry\perl\bin\perl.exe" "C:\Strawberry\perl\lib\ExtUtils\xsubpp"  -typemap "C:\STRAWB~1\perl\lib\ExtUtils\typemap"  Curve25519.xs > Curve25519.xsc && "C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e mv -- Curve25519.xsc Curve25519.c
gcc -c  -I.     -s -O2 -DWIN32 -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2     -DVERSION=\"0.05\"    -DXS_VERSION=\"0.05\"  "-IC:\STRAWB~1\perl\lib\CORE"   Curve25519.c
Curve25519.xs: In function 'XS_Crypt__Curve25519_curve25519':
Curve25519.xs:47:26: error: expected identifier or '(' before '[' token
         unsigned char OUT[32];
                          ^
Curve25519.xs:78:29: error: expected expression before ',' token
         curve25519_donna(OUT, csk, bp);
                             ^
In file included from C:\STRAWB~1\perl\lib\CORE/perl.h:5470:0,
                 from Curve25519.xs:2:
C:\STRAWB~1\perl\lib\CORE/pp.h:326:58: error: expected expression before ')' token
 #define mXPUSHp(p,l) STMT_START { EXTEND(sp,1); mPUSHp((p), (l)); } STMT_END
                                                          ^
C:\STRAWB~1\perl\lib\CORE/pp.h:302:28: note: in definition of macro 'PUSHs'
 #define PUSHs(s) (*++sp = (s))
                            ^
C:\STRAWB~1\perl\lib\CORE/pp.h:319:27: note: in expansion of macro 'newSVpvn_flags'
 #define mPUSHp(p,l) PUSHs(newSVpvn_flags((p), (l), SVs_TEMP))
                           ^
C:\STRAWB~1\perl\lib\CORE/pp.h:326:49: note: in expansion of macro 'mPUSHp'
 #define mXPUSHp(p,l) STMT_START { EXTEND(sp,1); mPUSHp((p), (l)); } STMT_END
                                                 ^
Curve25519.xs:80:9: note: in expansion of macro 'mXPUSHp'
         mXPUSHp(OUT, 32);
         ^
dmake.exe:  Error code 129, while making 'Curve25519.o'

**Comment by sisyphus** [comment]
Looks to me (not thoroughly checked) that the symbol OUT is a macro on Windows, and that the simplest solution is (in the xs file) to rename "OUT" to something that's not going to clash - eg "o".

**Comment by ajgb** [comment]
Could you test just released version 0.06?

Thank you,
Alex

**Comment by twogee** [comment]
Builds on macOS with a grumble about keybuffer (defined as array of unsigned 8 bit integers) being converted to char (signed 8 bit integers) through use of PUSH macros from CORE. Passes all tests. 👍
