### ISSUE TITLE
Installation fails on macOS

### ISSUE THREAD

**Issue by twogee** [ajgb/crypt-curve25519#4]
... because curve25519-donna.c is compiled with "-m32" flag resulting in 32 bit curve25519-donna.a library subsequently ignored by the linker. The wrong flag is selected because $Config{archname} is reported as darwin-thread-multi-2level; check $Config{cppsymbols} instead.

**Comment by whindsx** [comment]
Same with SunOS 5.11 in my case $Config{archname} is i86pc-solaris-thread-multi-64. Using $Config{cppsymbols} worked. Thanks.

**Comment by ajgb** [comment]
Could you test just released version 0.06?

Thank you,
Alex

**Comment by twogee** [comment]
🥇 see my comment on #2

**Comment by whindsx** [comment]
Built and tested without issue on SunOS 5.11 (Solaris 11.3). Thanks.
